# Generated by Django 5.0 on 2023-12-18 15:41

from django.db import migrations

from task.models import (
    StatusEnum,
    TaskStatusModel,
    TypeEnum,
    TaskTypeModel,
    FileTypeEnum,
    FileType,
)


def fill_reference_data(apps, schema_editor):
    for status_enum in StatusEnum:
        TaskStatusModel.objects.create(code=status_enum.value, name=status_enum.value)

    for type_enum in TypeEnum:
        TaskTypeModel.objects.create(code=type_enum.value, name=type_enum.value)

    for file_type_enum in FileTypeEnum:
        FileType.objects.create(code=file_type_enum.value, name=file_type_enum.value)


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [migrations.RunPython(fill_reference_data)]
