# Generated by Django 5.0 on 2023-12-20 16:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_init_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskYouTubeLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="task.taskmodel"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
